# Generated by Django 4.2.16 on 2024-10-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('years', models.PositiveIntegerField(blank=True, null=True)),
                ('probe_date', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('arterial_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('gw', models.IntegerField(blank=True, null=True)),
                ('baby_weight', models.IntegerField(blank=True, null=True)),
                ('erythrocytes', models.FloatField(blank=True, null=True)),
                ('hemoglobin', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Patients',
                'managed': False,
            },
        ),
    ]
